services:

  traefik:
    image: traefik:latest
    container_name: traefik

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxynet

      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.dashboard.entrypoints=https
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth

      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_HASH_PASSWORD}

    ports:
      - "80:80"
      - "443:443"
    
    restart: always

    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxynet"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.https.http.tls.certResolver=le"

      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/certificates/acme.json"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # add Let's Encrypt certs
      - ./certificates:/certificates


  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto

    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mosquitto/passwdfile:/mosquitto/config/passwdfile:rw


  mqtt-web:
    image: emqx/mqttx-web
    container_name: mqtt-web

    labels:
      - traefik.enable=true
      - traefik.http.routers.mqtt.rule=Host(`mqtt.${DOMAIN}`)
      - traefik.http.routers.mqtt.entrypoints=https
      - traefik.http.routers.mqtt.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_HASH_PASSWORD}


  server:
    container_name: server

    build:
      context: ./backend
      dockerfile: ./dockerfile

    env_file:
      - .env

    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_BROKER_USER=${MQTT_BROKER_USER}
      - MQTT_BROKER_PASSWORD=${MQTT_BROKER_PASSWORD}

    depends_on:
      - mosquitto

networks:
  default:
    name: proxynet
    external: true