networks:
  traefik-public:
    external: true


volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local


services:
  traefik:
    image: traefik:latest
    container_name: traefik

    ports:
      - "80:80"
      - "8080:8080"
    
    restart: always

    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"

      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik-public"

      - "--log.level=DEBUG"

    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)
    
    networks:
      - traefik-public

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # db:
  #   image: postgres:latest
  #   container_name: postgresql_db

  #   ports:
  #     - "5432:5432"

  #   env_file:
  #     - .env

  #   environment:
  #     - POSTGRES_USER=value
  #     - POSTGRES_PASSWORD=value
  #     - POSTGRES_DB=value

  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data


  # adminer:
  #   image: adminer
  #   restart: always
  #   networks:
  #     - backend
  #   depends_on:
  #     - db
  #   environment:
  #     - ADMINER_DESIGN=pepa-linha-dark
  #   labels:
  #     - traefik.enable=true

  #     - traefik.docker.network=backend
  #     - traefik.constraint-label=backend

  #     - traefik.http.routers.adminer-http.rule=Host(`adminer.localhost`)
  #     - traefik.http.routers.adminer-http.entrypoints=http
  #     - traefik.http.routers.adminer-http.middlewares=https-redirect
  #     - traefik.http.routers.adminer-https.rule=Host(`adminer.localhost`)
  #     - traefik.http.routers.adminer-https.entrypoints=https
  #     - traefik.http.routers.adminer-https.tls=true
  #     - traefik.http.routers.adminer-https.tls.certresolver=le
  #     - traefik.http.services.adminer.loadbalancer.server.port=8080


  # mosquitto:
  #   image: eclipse-mosquitto:latest
  #   container_name: mosquitto

  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"

  #   volumes:
  #     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
  #     - ./mosquitto/passwdfile:/mosquitto/config/passwdfile:rw


  # mqtt-web:
  #   image: emqx/mqttx-web
  #   container_name: mqtt-web

  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.mqtt.rule=Host(`mqtt.localhost`)"


  redis:
    image: redis:latest
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - traefik-public


  backend:
    container_name: backend

    build:
      context: ./backend
      dockerfile: ./dockerfile

    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

    env_file:
      - .env

    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.routers.backend-http.rule=Host(`api.localhost`)
      - traefik.http.services.backend-http.loadbalancer.server.port=8000
    
    networks:
      - traefik-public


  celery_worker:
    container_name: celery-worker
    build: ./backend

    command: bash scripts/celery_worker_start.sh

    volumes:
      - ./backend:/app

    env_file:
      - .env

    environment:
      - CELERY_BROKER_SCHEME=${CELERY_BROKER_SCHEME}
      - CELERY_BROKER_HOST=${CELERY_BROKER_HOST}
      - CELERY_BROKER_PORT=${CELERY_BROKER_PORT}
      - CELERY_BROKER_PASSWORD=${CELERY_BROKER_PASSWORD}
      - CELERY_BROKER_DB=${CELERY_BROKER_DB}

      - CELERY_BACKEND_SCHEME=${CELERY_BACKEND_SCHEME}
      - CELERY_BACKEND_HOST=${CELERY_BACKEND_HOST}
      - CELERY_BACKEND_PORT=${CELERY_BACKEND_PORT}
      - CELERY_BACKEND_PASSWORD=${CELERY_BACKEND_PASSWORD}
      - CELERY_BACKEND_DB=${CELERY_BACKEND_DB}

    networks:
      - traefik-public

    depends_on:
      - backend
      - redis


  flower:
    container_name: celery-flower
    build: ./backend

    command: celery -A app.background.worker.celery --broker=redis://redis:6379/0 flower --port=5555 

    ports:
      - "5555:5555"

    env_file:
      - .env

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.routers.flower.rule=Host(`flower.localhost`)
      - traefik.http.services.flower.loadbalancer.server.port=5555

    depends_on:
      - redis

    networks:
      - traefik-public