FROM python:3.12.6

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/local/app/

RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

ENV PYTHONPATH=./app/

COPY ./pyproject.toml ./poetry.lock /usr/local/app/

ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --only main ; fi"

COPY . /usr/local/app/

CMD ["python", "-m", "app.server.main"]